services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ddx
      MYSQL_USER: nestuser
      MYSQL_PASSWORD: nestpass
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      
  nestjs:
    build:
      context: .
      dockerfile: DockerFile
    container_name: nestjs
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: mysql://nestuser:nestpass@db:3306/ddx
      JWT_SECRET: access-key
      JWT_REFRESH_SECRET: refresh-key
    command: sh -c "sleep 10 && npx prisma generate && npm run start:prod"

volumes:
  db_data:
